### ISSUE TITLE
Feature Request: Display valid error message when using cli to load jobs

### ISSUE THREAD

**Issue by mumblez** [rundeck/rundeck-cli#198]
rd version: 1.0.29
debian / linux
rundeck version: 2.11.6

When uploading jobs with the cli tool and it fails, it's often unclear why it failed, e.g. 

```text
# rd jobs load -F yaml -d update -p Playground -r -v -f job.rundeck.yaml
# 1 Jobs Failed:
org.rundeck.client.api.model.JobItem{id='777822ad-08e6-4049-959f-fff629684804', name='debug', group='Example', project='Playground', description='null', href='https://<redacted>/api/24/job/777822ad-08e6-4049-959f-fff629684804', permalink='https://<redacted>/project/Playground/job/show/777822ad-08e6-4049-959f-fff629684804'}
```
but if I upload the same job via the web ui, I get a really helpful error message, e.g.

![web-ui-error](https://user-images.githubusercontent.com/4791540/46178710-d85f7500-c2af-11e8-80cd-b07a941a27a1.jpg)

Not sure whether to classify this as a bug or a feature request but if we can send the same error message to the cli tool that would be really helpful.

Here's the job definition I used to debug -

```yaml
- description: |-
    Example
  executionEnabled: true
  defaultTab: output
  group: Example
  loglevel: INFO
  name: debug
  nodeFilterEditable: false
  options:
  - description: first arg
    name: first
    required: true
    enforce: true
    # Trigger an error by not setting a default value!!!
    #value: John
    values:
    - John
    - Sarah
  - description: second arg
    name: second
    required: true
    value: Doe
  schedule:
    month: '*'
    time:
      hour: '23'
      minute: '00'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - exec: '{ echo; echo $RD_OPTION_FIRST; echo $RD_OPTION_SECOND; }'
    keepgoing: false
    strategy: node-first
 
```
