### ISSUE TITLE
Simple data format used for `-v` verbose output has weird indentation

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck-cli#323]
e.g. output from `rd jobs list -p test3 -v`

The `id:` is not indented but the other attributes are.  There is no separator char between data items.

```
# 2 Jobs in project test3
id: 4ed0ea80-cc42-4ace-b905-9f7ebd828a92
  name: child
  project: test3
  href: http://outatime.local:4440/api/35/job/4ed0ea80-cc42-4ace-b905-9f7ebd828a92
  permalink: http://outatime.local:4440/project/test3/job/show/4ed0ea80-cc42-4ace-b905-9f7ebd828a92
  description: 

id: 31185ae0-f822-4749-b764-78950c6c323c
  name: parent
  project: test3
  href: http://outatime.local:4440/api/35/job/31185ae0-f822-4749-b764-78950c6c323c
  permalink: http://outatime.local:4440/project/test3/job/show/31185ae0-f822-4749-b764-78950c6c323c
  description: 
```
