### ISSUE TITLE
rd jobs list idlist not full configuration

### ISSUE THREAD

**Issue by suslikas** [rundeck/rundeck-cli#372]
Hi,

I use rd cli for bootstrap rundeck from ansible. This command not provide information about slack notification.

```
rd jobs list --idlist {{ item.job_id }} -p {{ item.project }} --format yaml --file {{ rd_tmp_dir.path }}/{{ item.job_id }}.yml
```

But this information present in export via rundeck Web UI.

```
  notification:
    onfailure:
      plugin:
        configuration:
          slack_channel: info-rundeck
          webhook_base_url: https://hooks.slack.com/services
          webhook_token: T01D...MGC
        type: SlackNotification
  notifyAvgDurationThreshold: null
```

OS: Debian 10
rundeck: 3.3.6.20201111-1
rundeck-cli: 1.3.10-1
openjdk: 1.8.0_292
