### ISSUE TITLE
[FEATURE REQUEST] : add the possibility in "rd acl create" to make rights on several resources without changing acl

### ISSUE THREAD

**Issue by gaillard-corentin** [rundeck/rundeck-cli#413]
Hi,

I tried to put rights on several resources in a single ACL. 
example :
`rd acl create -c project -p 'my_project' -a '*' -g my_group --adhoc --job "*"`
```
# create or append this to a .aclpolicy file
---
by:
  group: my_group
context:
  project: my_project
for:
  job:
  - allow: '*'
    equals:
      name: '*'
      group: ''
description: generated

```
`rd acl create -c project -p 'my_project' -a '*' -g my_group --adhoc`
```
# create or append this to a .aclpolicy file
---
by:
  group: my_group
context:
  project: my_project
for:
  adhoc:
  - allow: '*'
description: generated
```

feel free to tell me if I'm doing it wrong.

Thanks !

**Comment by gschueler** [comment]
you can append two policies together separated by `---` on a single line.

If that doesn't answer your question, I'm not quite sure what you are trying to achieve.

You can also ask the rundeck mailing list or the [pagerduty process-automation community site](https://community.pagerduty.com/forum/c/process-automation) about usage.

**Comment by gaillard-corentin** [comment]
target : 
```
# create or append this to a .aclpolicy file
---
by:
  group: my_group
context:
  project: my_project
for:
  adhoc:
  - allow: '*'
  job:
  - allow: '*'
    equals:
      name: '*'
      group: ''
description: generated
```

instead of :

```
# create or append this to a .aclpolicy file
---
by:
  group: my_group
context:
  project: my_project
for:
  job:
  - allow: '*'
    equals:
      name: '*'
      group: ''
description: generated
# create or append this to a .aclpolicy file
---
by:
  group: my_group
context:
  project: my_project
for:
  adhoc:
  - allow: '*'
description: generated
```

I need these to avoid making a lot of different policies for user groups that need a lot of rights.
But also because I need to do a lot of groups.

Thanks !
