### ISSUE TITLE
Result of 'rd projects scm config' is not applicable for 'rd projects scm setup': ERROR: missing username or roles

### ISSUE THREAD

**Issue by vifrrg** [rundeck/rundeck-cli#518]
rd cli version: 2.0.6
rundeck version: 4.17.0

1. Create a project `someProject`. No matter how.
2. Configure *SCM git-import plugin*  for this project via *GUI*.
3. Export *JSON* configuration via `rd projects scm config --project=someProject --integration=import --file=someProject-scm.json`
4. Import the same configuration without changes using `rd projects scm setup --project=someProject --integration=import --file=someProject-scm.json --type=git-import`

Result: configuration is imported but cannot be enabled. Even if I make `rd projects scm enable` command which says `OK`. Even if I simply press *Enable* button in the *GUI*. To make it work I have to open *SCM* sttings in the *GUI* and then press *Save* button without any changes.

Rundeck error log says:
```
ERROR services.ScmService - SCM import config not valid (missing username or roles) for project: someProject ScmPluginConfig{, prefix='scm.import', type='git-import', enabled='true', config='...
```

**Comment by gschueler** [comment]
Have you tried using the API directly? it may be an issue with Rundeck, not the rd-cli itself.  If using the API directly has the same problem, it will require a fix in rundeck

**Comment by vifrrg** [comment]
@gschueler , yes.
Using the same *JSON* definition as in orignal case with *RD CLI* and [this REST API call](https://docs.rundeck.com/docs/api/rundeck-api.html#setup-scm-plugin-for-a-project) I am unable to reproduce the error.
SCM is configured correctly and comes to *enabled* status without additional actions.

**Comment by gschueler** [comment]
@vifrrg thanks for checking, I will look into the rd-cli behavior

**Comment by gschueler** [comment]
@vifrrg I was not able to reproduce the issue.  you can try setting env var `RD_DEBUG=3` before executing the `rd` commands, it will show the API requests.  If using the API directly works for you and using `rd` does not, maybe you can spot a difference in the API request performed by `rd`.  However, I examined the code and it looks correct, and in my tests it seemed to work correctly.  I tested against Rundeck OSS 4.17.0 and Process Automation 4.17.0

**Comment by vifrrg** [comment]
@gschueler , checked again.
Reproduced.
Taking into account there is Apache redirection configured for my case and some admin role is re-defined with *.aclpolicy* I started to lift those down.
First I re-configured *.aclpolicy* to make my user a full admin.
Did not work.
Second I moved a full Rundeck + PostreSQL Docker-composition (with docker-compose.yml) to my localhost and got rid of Apache + unset `RUNDECK_SERVER_REDIRECT` environment variable + changed `RUNDECK_GRAILS_URL` to `http://127.0.0.1:4440` + got rid of LDAP user authentication in favour of default `propertyFileLoginModule` way.

Works fine, behaviour described in the summary is not re-produced.

I'm not sure what is the case to catch an error agian, but surely one of:
- Buggy Apache + SSL proxy redirection.
- Buggy LDAP authentication.
- Buggy `RUNDECK_SERVER_REDIRECT` + `RUNDECK_GRAILS_URL` behaviour.

But sure this should be fixed not in CLI.
Closing the issue.
Thanks.

**Comment by gschueler** [comment]
@vifrrg thanks. My guess is that `missing username or roles` would happen only in a case where the authorization context that rundeck is using was not able to get a list of Role/Group names. So if you are still hunting down the problem, it might be something to do with the LDAP authentication.

**Comment by vifrrg** [comment]
@gschueler , I've got it.
The cause is that technical user is not a member of any group and then have no roles calculated by Rundeck.
Regardless I specify admin privileges for this user directly in *.aclpolicy* file like this:
```
description: Admin project level access control. Applies to resources within a specific project.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes

by:
  group: "someAdminGroup"
  username: "someTechnicalUser"

---

description: Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: "someAdminGroup"
  username: "someTechnicalUser"
```
When I add `someTechnicakUser` to `SomeAdminGroup` in the *LDAP* problem has gone.
I do not think this behaviour is correct, seems I have to create Rundeck issue.
