### ISSUE TITLE
rd run crashes with exception com.fasterxml.jackson.databind.JsonMappingException

### ISSUE THREAD

**Issue by Alveel** [rundeck/rundeck-cli#89]
Hi, I recently updated from 1.0.7 to 1.0.9 and now every job I run crashes with exception `com.fasterxml.jackson.databind.JsonMappingException` after filling in my password (I have RD_URL and RD_USER in my rd.conf).

I've tried running jobs with id, name, etc. to no avail. I've tried to trigger the exception doing other tasks such as listing jobs, executions, administrating the scheduler but that all seems to work fine.

Rundeck API Client Tool (v1.0.9)

Java version:
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
Rundeck version:
```
rundeck:
  version: 2.7.2
  build: 2.7.2-1
  node: internal
  base: /var/lib/rundeck
  apiversion: 18
```

I saw the default API version was updated to 19, maybe this is related?

Thanks!
